[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_BASE_URL = "https://tom.perpedes.dev/perpedes-pim/shop"

[context.branch-deploy.environment]
  VITE_BASE_URL = "https://capy.perpedes.dev/perpedes-pim/shop"